# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pyxchange', '0001_initial'), ('pyxchange', '0002_auto_20160816_2324'), ('pyxchange', '0003_auto_20160816_2327'), ('pyxchange', '0004_auto_20160816_2332'), ('pyxchange', '0005_auto_20160816_2352'), ('pyxchange', '0006_auto_20160816_2355'), ('pyxchange', '0007_auto_20160817_0001'), ('pyxchange', '0008_auto_20160817_0003'), ('pyxchange', '0009_auto_20160817_0005'), ('pyxchange', '0010_auto_20160817_0006'), ('pyxchange', '0011_auto_20160817_0007'), ('pyxchange', '0012_auto_20160817_2057'), ('pyxchange', '0013_auto_20160817_2100'), ('pyxchange', '0014_auto_20160817_2105'), ('pyxchange', '0015_auto_20160818_0059'), ('pyxchange', '0016_auto_20160818_0124'), ('pyxchange', '0017_image_upl_date'), ('pyxchange', '0018_auto_20160818_0133'), ('pyxchange', '0019_auto_20160818_1349'), ('pyxchange', '0020_auto_20160818_1358'), ('pyxchange', '0021_auto_20160818_1415'), ('pyxchange', '0022_auto_20160818_1415'), ('pyxchange', '0023_auto_20160818_1415'), ('pyxchange', '0024_auto_20160818_1417'), ('pyxchange', '0025_auto_20160818_1639'), ('pyxchange', '0026_auto_20160818_1647'), ('pyxchange', '0027_auto_20160818_1650'), ('pyxchange', '0028_auto_20160819_1419'), ('pyxchange', '0029_auto_20160819_1527'), ('pyxchange', '0030_auto_20160819_1623'), ('pyxchange', '0031_image_user'), ('pyxchange', '0032_auto_20160823_1746'), ('pyxchange', '0033_remove_like_if_like'), ('pyxchange', '0034_auto_20160824_0007'), ('pyxchange', '0035_auto_20160824_1846')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='%I', verbose_name='Image')),
                ('desc', models.CharField(help_text='Up to 500 char.', max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(max_length=6, unique=True)),
                ('rev_date', models.DateTimeField(null=True, verbose_name='Last reviewed')),
                ('rev_count', models.PositiveIntegerField(default=0, verbose_name='Reviews')),
                ('upl_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
            ],
        ),
    ]
