# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=1000)),
                ('key', models.SlugField(unique=True)),
                ('upload_date', models.DateTimeField()),
                ('last_review_date', models.DateTimeField()),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
