# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0002_auto_20160816_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='last_review_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
