# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0005_auto_20160816_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(help_text='Up to 500 fancy schmancy characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.SlugField(help_text='Automatically generated', max_length=6, unique=True),
        ),
    ]
