# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0006_auto_20160816_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(help_text='Up to 500 fancy schmancy characters', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
