# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0009_auto_20160817_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.SlugField(help_text='Automatically generated', max_length=6, unique=True),
        ),
    ]
