# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0013_auto_20160817_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='%I', verbose_name='Image'),
        ),
    ]
