# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0014_auto_20160817_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rev_date',
            field=models.DateTimeField(null=True, verbose_name='Last reviewed'),
        ),
    ]
