# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0015_auto_20160818_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='key',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='upl_date',
        ),
    ]
