# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0016_auto_20160818_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upl_date',
            field=models.DateTimeField(null=True, verbose_name='Uploaded'),
        ),
    ]
