# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0017_image_upl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upl_date',
            field=models.DateTimeField(verbose_name='Uploaded'),
        ),
    ]
