# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0018_auto_20160818_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upl_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Uploaded'),
        ),
    ]
