# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0029_auto_20160819_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rev_date',
            field=models.DateTimeField(null=True, verbose_name='Last reviewed'),
        ),
    ]
