# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyxchange', '0031_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='like_count',
        ),
        migrations.AddField(
            model_name='like',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxchange.Image'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
