# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0032_auto_20160823_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='if_like',
        ),
    ]
