# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxchange', '0033_remove_like_if_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
